version: "3.1"

services:
  postgres-e2e-org:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: organization
      POSTGRES_HOST: root
      POSTGRES_USER: root
    ports:
      - 5432:5432